initIdfile <- function () {
    Sys.chmod(system.file("conduit.key", package = "conduit"), mode = "0400")
    assign("defaultIdfile",
           system.file("conduit.key", package = "conduit"),
           .conduit.global)
}

#' Creates module output directory on host
#'
#' @details Directory to be created is given by \code{host$directory}
#'
#' @param host remote host list
#'
#' @seealso \code{runModule}
#'
#' @return 0 if success
createHostDirectory <- function(host) {
    user <- host$user
    address <- host$address
    port <- host$port
    directory <- host$directory
    idfile <- host$idfile
    args <- c("-i", idfile,
              "-p", port,
              paste0(user, "@", address),
              paste("'mkdir -p", directory, "'"))
    result <- system2("ssh", args)
    return(result)
}

#' Copy a file to remote module host
#'
#' @details copies file at \code{file} to remote directory
#' \code{host$directory}.
#'
#' @param file file to copy
#' @param host host list
#' @param idfile login credentials
#'
#' @seealso \code{runModule}
#'
#' @return 0 if successful
fileToHost <- function(file, host,
                       idfile = get("defaultIdfile", envir = .conduit.global)) {
    user <- host$user
    address <- host$address
    port <- host$port
    directory <- host$directory
    
    args <- c("-i", idfile,
              "-P", port,
              file,
              paste0(user, "@", address, ":", directory))
    result <- system2("scp", args)
    return(result)
}

#' Fetch file from remote host.
#'
#' @details copies file at \code{file} from remote directory
#' \code{host$directory} to the current working directory.
#'
#' @param file file path
#' @param host host list
#'
#' @return 0 if successful
fetchFromHost <- function(file, host) {
    user <- host$user
    address <- host$address
    port <- host$port
    directory <- host$directory
    idfile <- host$idfile

    args <- c("-i", idfile,
              "-P", port,
              paste0(user, "@", address, ":",
                     file.path(directory, file, fsep = "/")),
              ".")
    result <- system2("scp", args)
    return(result)
}

#' Parse a module's host
#'
#' Parse the the host attribute from a \code{module} object.
#'
#' @details Default user = 'conduit', default port = '22'.
#'
#' \code{directory} slot is filled by a random output directory to be
#' created on the remote host at \code{/tmp/{sessionID}/}
#'
#' @param host module host as character string
#' @param idfile authentication key
#'
#' @return list of \itemize{
#'   \item user
#'   \item password
#'   \item address
#'   \item port
#'   \item directory
#'   \item idfile}
parseModuleHost <- function(host,
                            idfile = get("defaultIdfile",
                                         envir = .conduit.global)) {
    scheme = "ssh"
    if (grepl("://", host)) {
        pieces <- strsplit(host, "://")[[1]]
        scheme <- pieces[1]
        if (scheme != "ssh") {
            stop("Only SSH scheme supported for module hosts")
        }
        host <- pieces[2]
    }
    if (grepl("@", host)) {
        pieces <- strsplit(host, "@")[[1]]
        auth <- pieces[1]
        address <- pieces[2]
        if(grepl(":", auth)) {
            pieces <- strsplit(auth, ":")[[1]]
            user <- pieces[1]
            password <- pieces[2]
        } else {
            user <- auth
            password <- ""
        }
    } else {
        user <- "conduit"
        password <- ""
        address <- host
    }
    if (grepl(":", address)) {
        pieces <- strsplit(address, ":")[[1]]
        address <- pieces[1]
        port <- pieces[2]
    } else {
        port <- "22"
    }
    if (grepl("/", port)) {
        split <- regexpr("/", port)
        directory <- substr(port, split, nchar(port))
        port <- substr(port, 1, split - 1)
    } else {
        directory <-
            file.path("/tmp", get("sessionID", envir = .conduit.global),
                      basename(tempfile("module")), fsep="/")
    }
    host <- list(user = user, password = password, address = address,
                 port = port, directory = directory, idfile = idfile)
    return(host)
}

#' Build a host string from a parsed host list
#'
#' @param parsedHost list generated by \code{parseModuleHost}
#'
#' @return character string describing module host
buildModuleHost <- function (parsedHost) {
    host <- paste0(parsedHost$user, "@", parsedHost$address, ":",
                   parsedHost$port)
    return(host)
}
